CREATE OR REPLACE FUNCTION DISABLE_RLS_FOR_TABLE(table_name TEXT) RETURNS VOID AS $$
BEGIN
  EXECUTE 'ALTER TABLE ' || quote_ident(table_name) || ' DISABLE ROW LEVEL SECURITY';
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION ENABLE_RLS_FOR_TABLE(table_name TEXT) RETURNS VOID AS $$
BEGIN
  EXECUTE 'ALTER TABLE ' || quote_ident(table_name) || ' ENABLE ROW LEVEL SECURITY';
END;
$$ LANGUAGE plpgsql;
